"""Initial tables

Revision ID: 4439a3f4c80e
Revises: 
Create Date: 2026-04-08 11:31:19.622848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4439a3f4c80e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constructions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gid', sa.String(), nullable=False, comment='ID с сайта boards.by (из URL или карточки). Генерировать нельзя!'),
    sa.Column('address', sa.String(), nullable=False, comment='Полный адрес: «г. Минск, пр. Независимости, 100»'),
    sa.Column('lon', sa.Float(), nullable=False, comment='Долгота (десятичный формат, напр. 27.5766)'),
    sa.Column('lat', sa.Float(), nullable=False, comment='Широта (десятичный формат, напр. 53.9)'),
    sa.Column('construction_format', sa.String(), nullable=False, comment='Нормализованный формат конструкции. Варианты: Билборды, Арки, Мосты, Брандмауэры, Ситиборды, Сити-форматы, Нетиповые форматы'),
    sa.Column('display_type', sa.String(), nullable=True, comment='Нормализованный тип отображения. Варианты: Призматрон, Скроллер, Видеоэкран, Статика, null'),
    sa.Column('lighting', sa.Boolean(), nullable=True, comment='Подсветка: true = есть, false = нет, null = неизвестно'),
    sa.Column('source_url', sa.String(), nullable=True, comment='URL карточки на boards.by'),
    sa.Column('raw_data', sa.Text(), nullable=True, comment='Сырой JSON с сайта (для отладки)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constructions_gid'), 'constructions', ['gid'], unique=True)
    op.create_index(op.f('ix_constructions_id'), 'constructions', ['id'], unique=False)
    op.create_table('construction_sides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('construction_id', sa.Integer(), nullable=False, comment='Ссылка на родительскую конструкцию'),
    sa.Column('name', sa.String(), nullable=False, comment='Название стороны: А, Б, А1 и т.д. Если сторон нет — gid'),
    sa.Column('size', sa.String(), nullable=True, comment='Нормализованный размер: «6x3», «3.4x1.8». Формат: Ширина x Высота'),
    sa.Column('material', sa.String(), nullable=True, comment='Материал поверхности (баннер, самоклейка и т.д.)'),
    sa.Column('display_type', sa.String(), nullable=True, comment='Призматрон / Скроллер / Видеоэкран / Статика / null'),
    sa.Column('lighting', sa.Boolean(), nullable=True, comment='Подсветка стороны: true / false / null'),
    sa.Column('source_url', sa.String(), nullable=True, comment='URL стороны на boards.by'),
    sa.Column('raw_data', sa.Text(), nullable=True, comment='Сырой JSON стороны (для отладки)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['construction_id'], ['constructions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('construction_id', 'name', name='uq_construction_side_name')
    )
    op.create_index(op.f('ix_construction_sides_construction_id'), 'construction_sides', ['construction_id'], unique=False)
    op.create_index(op.f('ix_construction_sides_id'), 'construction_sides', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_construction_sides_id'), table_name='construction_sides')
    op.drop_index(op.f('ix_construction_sides_construction_id'), table_name='construction_sides')
    op.drop_table('construction_sides')
    op.drop_index(op.f('ix_constructions_id'), table_name='constructions')
    op.drop_index(op.f('ix_constructions_gid'), table_name='constructions')
    op.drop_table('constructions')
    # ### end Alembic commands ###
